# Generated by Django 4.1.3 on 2023-04-15 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LittleLemonDRF', '0007_rename_user_id_cart_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='menuitem',
        ),
        migrations.AddField(
            model_name='cart',
            name='menuitem_test',
            field=models.TextField(default=''),
        ),
    ]
