# Generated by Django 4.1.3 on 2023-04-15 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LittleLemonDRF', '0008_remove_cart_menuitem_cart_menuitem_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='user',
        ),
    ]
