# Generated by Django 4.1.3 on 2023-04-15 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LittleLemonDRF', '0012_remove_cart_menuitem_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='user_token',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
