# Generated by Django 4.1.3 on 2023-04-15 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("LittleLemonDRF", "0018_alter_cart_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="menuitem",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.PROTECT,
                to="LittleLemonDRF.menuitem",
            ),
        ),
        migrations.AlterField(
            model_name="cart",
            name="user_token",
            field=models.CharField(default="", max_length=128),
        ),
    ]
