# Generated by Django 4.1.3 on 2023-04-15 15:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("LittleLemonDRF", "0019_alter_cart_menuitem_alter_cart_user_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="user",
            field=models.ForeignKey(
                db_column="user_id",
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.RenameField(
            model_name="cart",
            old_name="user",
            new_name="user_id",
        ),
    ]
