# Generated by Django 4.1.3 on 2023-04-15 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("LittleLemonDRF", "0020_alter_cart_user_rename_user_cart_user_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="menuitem",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="LittleLemonDRF.menuitem",
            ),
        ),
    ]
