# Generated by Django 4.1.3 on 2023-04-15 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("LittleLemonDRF", "0023_remove_cart_user_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="menuitem",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="LittleLemonDRF.menuitem",
            ),
        ),
    ]
