# Generated by Django 4.1.3 on 2023-04-15 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("LittleLemonDRF", "0025_alter_cart_menuitem_order"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Order",
        ),
    ]
