# Generated by Django 4.1.3 on 2023-04-15 18:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("LittleLemonDRF", "0026_delete_order"),
    ]

    operations = [
        migrations.CreateModel(
            name="Orders",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "delivery_status",
                    models.SmallIntegerField(choices=[(0, 0), (1, 1)], null=True),
                ),
                (
                    "orderitem",
                    models.ForeignKey(
                        db_column="order_item_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="LittleLemonDRF.menuitem",
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        db_column="user_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
